/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BathroomsRouteImport } from './routes/bathrooms'
import { Route as BedroomsRouteImport } from './routes/bedrooms'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DesignConceptsRouteImport } from './routes/design-concepts'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HomeOfficeRouteImport } from './routes/home-office'
import { Route as LivingRoomsRouteImport } from './routes/living-rooms'
import { Route as ModularKitchensRouteImport } from './routes/modular-kitchens'
import { Route as WardrobesRouteImport } from './routes/wardrobes'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BathroomsRoute = BathroomsRouteImport.update({
  id: '/bathrooms',
  path: '/bathrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const BedroomsRoute = BedroomsRouteImport.update({
  id: '/bedrooms',
  path: '/bedrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignConceptsRoute = DesignConceptsRouteImport.update({
  id: '/design-concepts',
  path: '/design-concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeOfficeRoute = HomeOfficeRouteImport.update({
  id: '/home-office',
  path: '/home-office',
  getParentRoute: () => rootRouteImport,
} as any)
const LivingRoomsRoute = LivingRoomsRouteImport.update({
  id: '/living-rooms',
  path: '/living-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ModularKitchensRoute = ModularKitchensRouteImport.update({
  id: '/modular-kitchens',
  path: '/modular-kitchens',
  getParentRoute: () => rootRouteImport,
} as any)
const WardrobesRoute = WardrobesRouteImport.update({
  id: '/wardrobes',
  path: '/wardrobes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathrooms': typeof BathroomsRoute
  '/bedrooms': typeof BedroomsRoute
  '/contact': typeof ContactRoute
  '/design-concepts': typeof DesignConceptsRoute
  '/estimate': typeof EstimateRoute
  '/gallery': typeof GalleryRoute
  '/home-office': typeof HomeOfficeRoute
  '/living-rooms': typeof LivingRoomsRoute
  '/modular-kitchens': typeof ModularKitchensRoute
  '/wardrobes': typeof WardrobesRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathrooms': typeof BathroomsRoute
  '/bedrooms': typeof BedroomsRoute
  '/contact': typeof ContactRoute
  '/design-concepts': typeof DesignConceptsRoute
  '/estimate': typeof EstimateRoute
  '/gallery': typeof GalleryRoute
  '/home-office': typeof HomeOfficeRoute
  '/living-rooms': typeof LivingRoomsRoute
  '/modular-kitchens': typeof ModularKitchensRoute
  '/wardrobes': typeof WardrobesRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathrooms': typeof BathroomsRoute
  '/bedrooms': typeof BedroomsRoute
  '/contact': typeof ContactRoute
  '/design-concepts': typeof DesignConceptsRoute
  '/estimate': typeof EstimateRoute
  '/gallery': typeof GalleryRoute
  '/home-office': typeof HomeOfficeRoute
  '/living-rooms': typeof LivingRoomsRoute
  '/modular-kitchens': typeof ModularKitchensRoute
  '/wardrobes': typeof WardrobesRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bathrooms'
    | '/bedrooms'
    | '/contact'
    | '/design-concepts'
    | '/estimate'
    | '/gallery'
    | '/home-office'
    | '/living-rooms'
    | '/modular-kitchens'
    | '/wardrobes'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bathrooms'
    | '/bedrooms'
    | '/contact'
    | '/design-concepts'
    | '/estimate'
    | '/gallery'
    | '/home-office'
    | '/living-rooms'
    | '/modular-kitchens'
    | '/wardrobes'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bathrooms'
    | '/bedrooms'
    | '/contact'
    | '/design-concepts'
    | '/estimate'
    | '/gallery'
    | '/home-office'
    | '/living-rooms'
    | '/modular-kitchens'
    | '/wardrobes'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BathroomsRoute: typeof BathroomsRoute
  BedroomsRoute: typeof BedroomsRoute
  ContactRoute: typeof ContactRoute
  DesignConceptsRoute: typeof DesignConceptsRoute
  EstimateRoute: typeof EstimateRoute
  GalleryRoute: typeof GalleryRoute
  HomeOfficeRoute: typeof HomeOfficeRoute
  LivingRoomsRoute: typeof LivingRoomsRoute
  ModularKitchensRoute: typeof ModularKitchensRoute
  WardrobesRoute: typeof WardrobesRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathrooms': {
      id: '/bathrooms'
      path: '/bathrooms'
      fullPath: '/bathrooms'
      preLoaderRoute: typeof BathroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedrooms': {
      id: '/bedrooms'
      path: '/bedrooms'
      fullPath: '/bedrooms'
      preLoaderRoute: typeof BedroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-concepts': {
      id: '/design-concepts'
      path: '/design-concepts'
      fullPath: '/design-concepts'
      preLoaderRoute: typeof DesignConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-office': {
      id: '/home-office'
      path: '/home-office'
      fullPath: '/home-office'
      preLoaderRoute: typeof HomeOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/living-rooms': {
      id: '/living-rooms'
      path: '/living-rooms'
      fullPath: '/living-rooms'
      preLoaderRoute: typeof LivingRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular-kitchens': {
      id: '/modular-kitchens'
      path: '/modular-kitchens'
      fullPath: '/modular-kitchens'
      preLoaderRoute: typeof ModularKitchensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wardrobes': {
      id: '/wardrobes'
      path: '/wardrobes'
      fullPath: '/wardrobes'
      preLoaderRoute: typeof WardrobesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BathroomsRoute: BathroomsRoute,
  BedroomsRoute: BedroomsRoute,
  ContactRoute: ContactRoute,
  DesignConceptsRoute: DesignConceptsRoute,
  EstimateRoute: EstimateRoute,
  GalleryRoute: GalleryRoute,
  HomeOfficeRoute: HomeOfficeRoute,
  LivingRoomsRoute: LivingRoomsRoute,
  ModularKitchensRoute: ModularKitchensRoute,
  WardrobesRoute: WardrobesRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
